# Generated by Django 3.2.8 on 2023-05-12 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Busket',
            new_name='Basket',
        ),
    ]
